# List of valid authors for DCC-EX News articles
authors:
  peteGSX:
    name: peteGSX
    description: Motorcycle nut
    avatar: https://gravatar.com/avatar/5bacea2f40da736dffbd90dd2fa05e4c?s=256&d=identicon
