nav:
  - Product List: products.md
  - EX-CommandStation: ex-commandstation
  - EX-CommandStation Booster 1 (EX-CSB1): ex-csb1
  - EX-FastClock: ex-fastclock
  - EX-IOExpander: ex-ioexpander
  - EX-Turntable: ex-turntable
