nav:
  - Home: index.md
  - News: news
  - Products: products
  - EXRAIL: exrail
  - EX-FastClock : exfastclock
  - Reference Manuals : reference
  - Experimenting with MkDocs: experimenting
  - Contributing: contributing
  