nav:
  - Home: index.md
  - Getting Started: getting-started
  - News: news
  - Products: products
  - Reference Manuals : reference
  - Glossary: glossary
  # - Experimenting with MkDocs: experimenting
  - Contributing: contributing
  