nav:
  - Home: index.md
  - Products: products
  - Purchasing: purchasing
  - Installing: installer
  - Self Build: diy
  - News: news
  - Support: support
  - Reference : reference
  - Contributing: contributing
  