nav:
  - Home: index.md
  - News: news
  - Products: products
  # - EXRAIL: exrail
  - Reference Manuals : reference
  - Glossary: glossary
  - Experimenting with MkDocs: experimenting
  - Contributing: contributing
  