nav:
  - Home: index.md
  - Getting Started: getting-started
  - Products: products
  - Purchasing: purchasing
  - News: news
  - Support: support
  - Reference : reference
  - Glossary: glossary
  - Contributing: contributing
  